# compose.yml:jeff
#
# Docker compose setup for InvenTree
#
---

networks:
  traefik-proxy:
    attachable: true
    external: true
    driver: overlay
  inventree-db:
  inventree-server:
#volumes:
#media:
#static:

services:
  # redis acts as database cache manager
  inventree-cache:
    env_file:
      - .env
    image: redis:7.0
    container_name: inventree-cache
    expose:
      - ${INVENTREE_CACHE_PORT:-6379}
    restart: always
    networks:
      #- inventree-server
      - traefik-proxy

  # Database service
  # Use PostgreSQL as the database backend
  inventree-db:
    image: postgres:13
    container_name: inventree-db
    expose:
      - ${INVENTREE_DB_PORT:-5432}/tcp
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdb
      - POSTGRES_USER=${INVENTREE_DB_USER:?You must provide the 'INVENTREE_DB_USER' variable in the .env file}
      - POSTGRES_PASSWORD=${INVENTREE_DB_PASSWORD:?You must provide the 'INVENTREE_DB_PASSWORD' variable in the .env file}
      - POSTGRES_DB=${INVENTREE_DB_NAME:?You must provide the 'INVENTREE_DB_NAME' variable in the .env file}
    volumes:
      # Map 'data' volume such that postgres database is stored externally
      - ${INVENTREE_EXT_VOLUME:?You must specify the 'INVENTREE_EXT_VOLUME' variable in the .env file!}:/var/lib/postgresql/data/:z
    restart: unless-stopped
    networks:
      #- inventree-server
      - traefik-proxy

  # InvenTree web server service
  # Uses gunicorn as the web server
  inventree-server:
    env_file:
      - .env
    image: inventree/inventree:${INVENTREE_TAG:-stable}
    container_name: inventree-server
    ports:
      - 8000/tcp
    expose:
      - 8000
    depends_on:
      - inventree-db
      - inventree-cache
    volumes:
      # Data volume must map to /home/inventree/data
      - ${INVENTREE_EXT_VOLUME}:/home/inventree/data:z
      #- static:/usr/src/static
      #- media:/usr/src/media
    restart: unless-stopped
    networks:
      #- inventree-server
      - traefik-proxy

  # Background worker process handles long-running or periodic tasks
  inventree-worker:
    env_file:
      - .env
    image: inventree/inventree:${INVENTREE_TAG:-stable}
    container_name: inventree-worker
    command: invoke worker
    depends_on:
      - inventree-server
    volumes:
      # Data volume must map to /home/inventree/data
      - ${INVENTREE_EXT_VOLUME}:/home/inventree/data:z
    restart: unless-stopped
    networks:
      #- inventree-server
      - traefik-proxy

  inventree-proxy:
    env_file:
      - .env
    container_name: inventree-proxy
    # https://hub.docker.com/_/nginx
    image: nginx:alpine
    restart: always
    depends_on:
      - inventree-server
    ports:
      - ${NGINX_WEB_PORT:-80}:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro,z
      - ${INVENTREE_EXT_VOLUME}:/var/www:z
      #- static:/var/www/inventree/static
      #- media:/var/www/inventree/media
    networks:
      #- inventree-server
      - traefik-proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.inventree-fs1.rule=Host(`inventory.fs1.home`) && PathPrefix(`/`)"
      - "traefik.http.routers.inventree-fs1.entrypoints=websecure"
      - "traefik.http.services.inventree-fs1.loadbalancer.server.port=80"
      - "traefik.http.routers.inventree-fs1.service=inventree-fs1"
      - "traefik.http.routers.inventree-fs1.tls.certresolver=staging-web-acme"
